#!/bin/sh

projectName="reactminimal"

mkdir $projectName

cd $projectName

npm init -y

python3 ../installpkg.py

echo 'PCFET0NUWVBFIGh0bWw+CjxodG1sPgogICAgPGhlYWQ+CiAgICAgICAgPG1ldGEgY2hhcnNldD0iVVRGLTgiIC8+CiAgICAgICAgPHRpdGxlPjwvdGl0bGU+CiAgICA8L2hlYWQ+CiAgICA8Ym9keT4KICAgICAgICA8ZGl2IGlkPSJyb290Ij48L2Rpdj4KICAgICAgICA8c2NyaXB0IHNyYz0iLi9ub2RlX21vZHVsZXMvcmVhY3QvdW1kL3JlYWN0LmRldmVsb3BtZW50LmpzIj48L3NjcmlwdD4KICAgICAgICA8c2NyaXB0IHNyYz0iLi9ub2RlX21vZHVsZXMvcmVhY3QtZG9tL3VtZC9yZWFjdC1kb20uZGV2ZWxvcG1lbnQuanMiPjwvc2NyaXB0PgogICAgICAgIDxzY3JpcHQgc3JjPSIuL2Rpc3QvbWFpbi5qcyI+PC9zY3JpcHQ+CiAgICA8L2JvZHk+CjwvaHRtbD4=' | base64 -d > index.html

echo 'ewogICAgInByZXNldHMiOiBbIkBiYWJlbC9wcmVzZXQtZW52IiwgIkBiYWJlbC9wcmVzZXQtcmVhY3QiXQp9' | base64 -d > .babelrc

echo 'bW9kdWxlLmV4cG9ydHMgPSB7CiAgbW9kdWxlOiB7CiAgICBydWxlczogWwogICAgICB7CiAgICAgICAgdGVzdDogL1wuanN4PyQvLAogICAgICAgIGV4Y2x1ZGU6IC9ub2RlX21vZHVsZXMvLAogICAgICAgIHVzZTogewogICAgICAgICAgbG9hZGVyOiAiYmFiZWwtbG9hZGVyIgogICAgICAgIH0KICAgICAgfQogICAgXQogIH0KfTs=' | base64 -d > webpack.config.js

echo 'ewogICJuYW1lIjogInJlYWN0bWluaW1hbCIsCiAgInZlcnNpb24iOiAiMS4wLjAiLAogICJkZXNjcmlwdGlvbiI6ICIiLAogICJtYWluIjogImluZGV4LmpzIiwKICAic2NyaXB0cyI6IHsKICAgICJ0ZXN0IjogImVjaG8gXCJFcnJvcjogbm8gdGVzdCBzcGVjaWZpZWRcIiAmJiBleGl0IDEiLAogICAgImJ1aWxkIjogIndlYnBhY2sgLS1tb2RlIGRldmVsb3BtZW50IgogIH0sCiAgImtleXdvcmRzIjogW10sCiAgImF1dGhvciI6ICIiLAogICJsaWNlbnNlIjogIklTQyIsCiAgImRldkRlcGVuZGVuY2llcyI6IHsKICAgICJAYmFiZWwvY29yZSI6ICJeNy4xMy44IiwKICAgICJAYmFiZWwvcHJlc2V0LWVudiI6ICJeNy4xMy45IiwKICAgICJAYmFiZWwvcHJlc2V0LXJlYWN0IjogIl43LjEyLjEzIiwKICAgICJiYWJlbC1sb2FkZXIiOiAiXjguMi4yIiwKICAgICJyZWFjdCI6ICJeMTcuMC4xIiwKICAgICJyZWFjdC1kb20iOiAiXjE3LjAuMSIsCiAgICAid2VicGFjayI6ICJeNS4yNC4yIiwKICAgICJ3ZWJwYWNrLWNsaSI6ICJeNC41LjAiCiAgfQp9Cg==' | base64 -d > package.json

mkdir -p src/components

touch src/components/app.jsx

echo 'aW1wb3J0ICogYXMgUmVhY3QgZnJvbSAicmVhY3QiOwoKZXhwb3J0IGNsYXNzIEFwcCBleHRlbmRzIFJlYWN0LkNvbXBvbmVudCB7CgogIHJlbmRlcigpIHsKICAgIHJldHVybiAoCiAgICAgIDxkaXY+CiAgICAgICAgSGVsbG8sIHdvcmxkIQogICAgICA8L2Rpdj4KICAgICk7CiAgfQp9' | base64 -d > src/components/app.jsx

echo 'aW1wb3J0IFJlYWN0RE9NIGZyb20gInJlYWN0LWRvbSI7CmltcG9ydCB7IEFwcCB9IGZyb20gIi4vY29tcG9uZW50cy9hcHAuanN4IjsKClJlYWN0RE9NLnJlbmRlcigKICA8QXBwIC8+LAogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJyb290IikKKTs=' | base64 -d > src/index.js

npm run build

firefox index.html || chrome index.html || chromium index.html
